### ISSUE TITLE
Folding coins - Windows Update

### ISSUE THREAD

**Issue by rollingsteam** [pkt-cash/www-pkt-cash#48]
To the Folding coin section need to add the directions to open the wallet first. 
If some one can point me to the page file in github, I can open up a PR.
I will clean up the wording in the PR, just brain storming.

Under here: 

Window Users:
 Step one: Open your wallet 
In the cmd propmt, navigate to the folder that holds pktcl.exe and run this command.
`cd <Path to the folder that holds pktcl.exe>`
You will want to enter in your this in your command terminal:

`pktctl.exe --wallet walletpassphrase <yourwalletpassphrase> <seconds to leave open>`

You will know that it is working, for no errors will show.  You will have a new line to enter in commands.
Step 2 fold coins

Now you can enter in this cmd  to fold your coins

`./bin/pktctl.exe --wallet sendfrom <address> 0 '["<address>"]'`

You will know this is working, for you will get a transaction number. You can match this transaction number up in the pkt block explorer

Or

you can put your wallet number in the pkt block explorer and search for it. You will see the Transactions table. 

- A Yellow circle means that the Transactions  is taking place.  Your balance will drop during this time. 
- A Green circle means that the Transactions  is complete. Your balance, will return to what is what is was before the folding occured.

Noticed how your Unconsolidated Txns is lowered.

**Comment by cjdelisle** [comment]
I think the place you want to edit is in https://github.com/pkt-cash/pkt-docs
Which incidentally is quite a bit easier to work in than this repo. Thanks for taking the time to contribute !
Caleb

**Comment by rollingsteam** [comment]
I made this issue in the correct place: https://github.com/pkt-cash/pkt-docs/issues/49
