### ISSUE TITLE
Broken image link. Missing image asset

### ISSUE THREAD

**Issue by 3rror404** [pkt-cash/www-pkt-cash#88]
In the TokenStrike section of this page https://pkt.cash/tech there is a broken image.

This is the relevant line:

https://github.com/pkt-cash/www-pkt-cash/blob/6cb31e474c39309bfa33324236f3bafc35b1fba7/pages/tech.vue#L55

Notice that "token" is spelt incorrectly. 

I would fix this myself but there doesn't seem to be a TokenStrike related image in the ```static/img``` directory to use.

**Comment by cjdelisle** [comment]
@coconut3-dev can you give me an opinion on this? ^^

**Comment by 3rror404** [comment]
This seems to have been fixed 👍
